spring:
  application:
    name: friday-im-server
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  nodeId: 1

server:
    port: 8989

netty:
  server:
    port: 8000
    address: 127.0.0.1

zk:
  address: 127.0.0.1:2181
  switch: true
  root: /router
  connection:
    timeout: 15000



app:
  im:
    serverport: