// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.friday.server.protobuf;

public final class FridayMessage {
  private FridayMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TEXT = 0;</code>
     */
    TEXT(0),
    /**
     * <code>PICTURE = 1;</code>
     */
    PICTURE(1),
    /**
     * <code>VOICE = 2;</code>
     */
    VOICE(2),
    /**
     * <code>VIDEO = 3;</code>
     */
    VIDEO(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TEXT = 0;</code>
     */
    public static final int TEXT_VALUE = 0;
    /**
     * <code>PICTURE = 1;</code>
     */
    public static final int PICTURE_VALUE = 1;
    /**
     * <code>VOICE = 2;</code>
     */
    public static final int VOICE_VALUE = 2;
    /**
     * <code>VIDEO = 3;</code>
     */
    public static final int VIDEO_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return TEXT;
        case 1: return PICTURE;
        case 2: return VOICE;
        case 3: return VIDEO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return FridayMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.MessageType)
  }

  /**
   * Protobuf enum {@code proto.ConverType}
   */
  public enum ConverType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>LOGIN = 0;</code>
     */
    LOGIN(0),
    /**
     * <pre>
     *会话
     * </pre>
     *
     * <code>MSG = 1;</code>
     */
    MSG(1),
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>PING = 2;</code>
     */
    PING(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *登录
     * </pre>
     *
     * <code>LOGIN = 0;</code>
     */
    public static final int LOGIN_VALUE = 0;
    /**
     * <pre>
     *会话
     * </pre>
     *
     * <code>MSG = 1;</code>
     */
    public static final int MSG_VALUE = 1;
    /**
     * <pre>
     *心跳
     * </pre>
     *
     * <code>PING = 2;</code>
     */
    public static final int PING_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ConverType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ConverType forNumber(int value) {
      switch (value) {
        case 0: return LOGIN;
        case 1: return MSG;
        case 2: return PING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ConverType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ConverType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ConverType>() {
            public ConverType findValueByNumber(int number) {
              return ConverType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return FridayMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final ConverType[] VALUES = values();

    public static ConverType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ConverType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.ConverType)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *服务消息ID
     * </pre>
     *
     * <code>uint64 requestId = 1;</code>
     * @return The requestId.
     */
    long getRequestId();

    /**
     * <pre>
     *客户端ID
     * </pre>
     *
     * <code>uint64 cid = 2;</code>
     * @return The cid.
     */
    long getCid();

    /**
     * <pre>
     *发送人ID
     * </pre>
     *
     * <code>string fromUid = 3;</code>
     * @return The fromUid.
     */
    java.lang.String getFromUid();
    /**
     * <pre>
     *发送人ID
     * </pre>
     *
     * <code>string fromUid = 3;</code>
     * @return The bytes for fromUid.
     */
    com.google.protobuf.ByteString
        getFromUidBytes();

    /**
     * <pre>
     *接收人ID
     * </pre>
     *
     * <code>string toUid = 4;</code>
     * @return The toUid.
     */
    java.lang.String getToUid();
    /**
     * <pre>
     *接收人ID
     * </pre>
     *
     * <code>string toUid = 4;</code>
     * @return The bytes for toUid.
     */
    com.google.protobuf.ByteString
        getToUidBytes();

    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>string groupId = 5;</code>
     * @return The groupId.
     */
    java.lang.String getGroupId();
    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>string groupId = 5;</code>
     * @return The bytes for groupId.
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string converId = 6;</code>
     * @return The converId.
     */
    java.lang.String getConverId();
    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string converId = 6;</code>
     * @return The bytes for converId.
     */
    com.google.protobuf.ByteString
        getConverIdBytes();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>.proto.MessageContent content = 7;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>.proto.MessageContent content = 7;</code>
     * @return The content.
     */
    FridayMessage.MessageContent getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>.proto.MessageContent content = 7;</code>
     */
    FridayMessage.MessageContentOrBuilder getContentOrBuilder();

    /**
     * <pre>
     *请求类型
     * </pre>
     *
     * <code>.proto.ConverType converType = 8;</code>
     * @return The enum numeric value on the wire for converType.
     */
    int getConverTypeValue();
    /**
     * <pre>
     *请求类型
     * </pre>
     *
     * <code>.proto.ConverType converType = 8;</code>
     * @return The converType.
     */
    FridayMessage.ConverType getConverType();
  }
  /**
   * Protobuf type {@code proto.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      fromUid_ = "";
      toUid_ = "";
      groupId_ = "";
      converId_ = "";
      converType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              requestId_ = input.readUInt64();
              break;
            }
            case 16: {

              cid_ = input.readUInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              fromUid_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              toUid_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              converId_ = s;
              break;
            }
            case 58: {
              FridayMessage.MessageContent.Builder subBuilder = null;
              if (content_ != null) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(FridayMessage.MessageContent.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }

              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              converType_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FridayMessage.internal_static_proto_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FridayMessage.internal_static_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FridayMessage.Message.class, FridayMessage.Message.Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <pre>
     *服务消息ID
     * </pre>
     *
     * <code>uint64 requestId = 1;</code>
     * @return The requestId.
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int CID_FIELD_NUMBER = 2;
    private long cid_;
    /**
     * <pre>
     *客户端ID
     * </pre>
     *
     * <code>uint64 cid = 2;</code>
     * @return The cid.
     */
    public long getCid() {
      return cid_;
    }

    public static final int FROMUID_FIELD_NUMBER = 3;
    private volatile java.lang.Object fromUid_;
    /**
     * <pre>
     *发送人ID
     * </pre>
     *
     * <code>string fromUid = 3;</code>
     * @return The fromUid.
     */
    public java.lang.String getFromUid() {
      java.lang.Object ref = fromUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromUid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送人ID
     * </pre>
     *
     * <code>string fromUid = 3;</code>
     * @return The bytes for fromUid.
     */
    public com.google.protobuf.ByteString
        getFromUidBytes() {
      java.lang.Object ref = fromUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOUID_FIELD_NUMBER = 4;
    private volatile java.lang.Object toUid_;
    /**
     * <pre>
     *接收人ID
     * </pre>
     *
     * <code>string toUid = 4;</code>
     * @return The toUid.
     */
    public java.lang.String getToUid() {
      java.lang.Object ref = toUid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        toUid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *接收人ID
     * </pre>
     *
     * <code>string toUid = 4;</code>
     * @return The bytes for toUid.
     */
    public com.google.protobuf.ByteString
        getToUidBytes() {
      java.lang.Object ref = toUid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        toUid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUPID_FIELD_NUMBER = 5;
    private volatile java.lang.Object groupId_;
    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>string groupId = 5;</code>
     * @return The groupId.
     */
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *群ID
     * </pre>
     *
     * <code>string groupId = 5;</code>
     * @return The bytes for groupId.
     */
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONVERID_FIELD_NUMBER = 6;
    private volatile java.lang.Object converId_;
    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string converId = 6;</code>
     * @return The converId.
     */
    public java.lang.String getConverId() {
      java.lang.Object ref = converId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        converId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *会话ID
     * </pre>
     *
     * <code>string converId = 6;</code>
     * @return The bytes for converId.
     */
    public com.google.protobuf.ByteString
        getConverIdBytes() {
      java.lang.Object ref = converId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        converId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 7;
    private FridayMessage.MessageContent content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>.proto.MessageContent content = 7;</code>
     * @return Whether the content field is set.
     */
    public boolean hasContent() {
      return content_ != null;
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>.proto.MessageContent content = 7;</code>
     * @return The content.
     */
    public FridayMessage.MessageContent getContent() {
      return content_ == null ? FridayMessage.MessageContent.getDefaultInstance() : content_;
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>.proto.MessageContent content = 7;</code>
     */
    public FridayMessage.MessageContentOrBuilder getContentOrBuilder() {
      return getContent();
    }

    public static final int CONVERTYPE_FIELD_NUMBER = 8;
    private int converType_;
    /**
     * <pre>
     *请求类型
     * </pre>
     *
     * <code>.proto.ConverType converType = 8;</code>
     * @return The enum numeric value on the wire for converType.
     */
    public int getConverTypeValue() {
      return converType_;
    }
    /**
     * <pre>
     *请求类型
     * </pre>
     *
     * <code>.proto.ConverType converType = 8;</code>
     * @return The converType.
     */
    public FridayMessage.ConverType getConverType() {
      @SuppressWarnings("deprecation")
      FridayMessage.ConverType result = FridayMessage.ConverType.valueOf(converType_);
      return result == null ? FridayMessage.ConverType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeUInt64(1, requestId_);
      }
      if (cid_ != 0L) {
        output.writeUInt64(2, cid_);
      }
      if (!getFromUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, fromUid_);
      }
      if (!getToUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, toUid_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, groupId_);
      }
      if (!getConverIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, converId_);
      }
      if (content_ != null) {
        output.writeMessage(7, getContent());
      }
      if (converType_ != FridayMessage.ConverType.LOGIN.getNumber()) {
        output.writeEnum(8, converType_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, requestId_);
      }
      if (cid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, cid_);
      }
      if (!getFromUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, fromUid_);
      }
      if (!getToUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, toUid_);
      }
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, groupId_);
      }
      if (!getConverIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, converId_);
      }
      if (content_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getContent());
      }
      if (converType_ != FridayMessage.ConverType.LOGIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, converType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FridayMessage.Message)) {
        return super.equals(obj);
      }
      FridayMessage.Message other = (FridayMessage.Message) obj;

      if (getRequestId()
          != other.getRequestId()) return false;
      if (getCid()
          != other.getCid()) return false;
      if (!getFromUid()
          .equals(other.getFromUid())) return false;
      if (!getToUid()
          .equals(other.getToUid())) return false;
      if (!getGroupId()
          .equals(other.getGroupId())) return false;
      if (!getConverId()
          .equals(other.getConverId())) return false;
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (converType_ != other.converType_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + CID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCid());
      hash = (37 * hash) + FROMUID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUid().hashCode();
      hash = (37 * hash) + TOUID_FIELD_NUMBER;
      hash = (53 * hash) + getToUid().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + CONVERID_FIELD_NUMBER;
      hash = (53 * hash) + getConverId().hashCode();
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (37 * hash) + CONVERTYPE_FIELD_NUMBER;
      hash = (53 * hash) + converType_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FridayMessage.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FridayMessage.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FridayMessage.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FridayMessage.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FridayMessage.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FridayMessage.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FridayMessage.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FridayMessage.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FridayMessage.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FridayMessage.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FridayMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FridayMessage.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FridayMessage.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Message)
        FridayMessage.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FridayMessage.internal_static_proto_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FridayMessage.internal_static_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FridayMessage.Message.class, FridayMessage.Message.Builder.class);
      }

      // Construct using com.friday.protobuf.FridayMessage.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestId_ = 0L;

        cid_ = 0L;

        fromUid_ = "";

        toUid_ = "";

        groupId_ = "";

        converId_ = "";

        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          content_ = null;
          contentBuilder_ = null;
        }
        converType_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FridayMessage.internal_static_proto_Message_descriptor;
      }

      @java.lang.Override
      public FridayMessage.Message getDefaultInstanceForType() {
        return FridayMessage.Message.getDefaultInstance();
      }

      @java.lang.Override
      public FridayMessage.Message build() {
        FridayMessage.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FridayMessage.Message buildPartial() {
        FridayMessage.Message result = new FridayMessage.Message(this);
        result.requestId_ = requestId_;
        result.cid_ = cid_;
        result.fromUid_ = fromUid_;
        result.toUid_ = toUid_;
        result.groupId_ = groupId_;
        result.converId_ = converId_;
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        result.converType_ = converType_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FridayMessage.Message) {
          return mergeFrom((FridayMessage.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FridayMessage.Message other) {
        if (other == FridayMessage.Message.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (other.getCid() != 0L) {
          setCid(other.getCid());
        }
        if (!other.getFromUid().isEmpty()) {
          fromUid_ = other.fromUid_;
          onChanged();
        }
        if (!other.getToUid().isEmpty()) {
          toUid_ = other.toUid_;
          onChanged();
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (!other.getConverId().isEmpty()) {
          converId_ = other.converId_;
          onChanged();
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        if (other.converType_ != 0) {
          setConverTypeValue(other.getConverTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FridayMessage.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FridayMessage.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long requestId_ ;
      /**
       * <pre>
       *服务消息ID
       * </pre>
       *
       * <code>uint64 requestId = 1;</code>
       * @return The requestId.
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <pre>
       *服务消息ID
       * </pre>
       *
       * <code>uint64 requestId = 1;</code>
       * @param value The requestId to set.
       * @return This builder for chaining.
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务消息ID
       * </pre>
       *
       * <code>uint64 requestId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private long cid_ ;
      /**
       * <pre>
       *客户端ID
       * </pre>
       *
       * <code>uint64 cid = 2;</code>
       * @return The cid.
       */
      public long getCid() {
        return cid_;
      }
      /**
       * <pre>
       *客户端ID
       * </pre>
       *
       * <code>uint64 cid = 2;</code>
       * @param value The cid to set.
       * @return This builder for chaining.
       */
      public Builder setCid(long value) {
        
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *客户端ID
       * </pre>
       *
       * <code>uint64 cid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCid() {
        
        cid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object fromUid_ = "";
      /**
       * <pre>
       *发送人ID
       * </pre>
       *
       * <code>string fromUid = 3;</code>
       * @return The fromUid.
       */
      public java.lang.String getFromUid() {
        java.lang.Object ref = fromUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fromUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送人ID
       * </pre>
       *
       * <code>string fromUid = 3;</code>
       * @return The bytes for fromUid.
       */
      public com.google.protobuf.ByteString
          getFromUidBytes() {
        java.lang.Object ref = fromUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送人ID
       * </pre>
       *
       * <code>string fromUid = 3;</code>
       * @param value The fromUid to set.
       * @return This builder for chaining.
       */
      public Builder setFromUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fromUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人ID
       * </pre>
       *
       * <code>string fromUid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFromUid() {
        
        fromUid_ = getDefaultInstance().getFromUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送人ID
       * </pre>
       *
       * <code>string fromUid = 3;</code>
       * @param value The bytes for fromUid to set.
       * @return This builder for chaining.
       */
      public Builder setFromUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fromUid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object toUid_ = "";
      /**
       * <pre>
       *接收人ID
       * </pre>
       *
       * <code>string toUid = 4;</code>
       * @return The toUid.
       */
      public java.lang.String getToUid() {
        java.lang.Object ref = toUid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          toUid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *接收人ID
       * </pre>
       *
       * <code>string toUid = 4;</code>
       * @return The bytes for toUid.
       */
      public com.google.protobuf.ByteString
          getToUidBytes() {
        java.lang.Object ref = toUid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          toUid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *接收人ID
       * </pre>
       *
       * <code>string toUid = 4;</code>
       * @param value The toUid to set.
       * @return This builder for chaining.
       */
      public Builder setToUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        toUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人ID
       * </pre>
       *
       * <code>string toUid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToUid() {
        
        toUid_ = getDefaultInstance().getToUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *接收人ID
       * </pre>
       *
       * <code>string toUid = 4;</code>
       * @param value The bytes for toUid to set.
       * @return This builder for chaining.
       */
      public Builder setToUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        toUid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object groupId_ = "";
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>string groupId = 5;</code>
       * @return The groupId.
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>string groupId = 5;</code>
       * @return The bytes for groupId.
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>string groupId = 5;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>string groupId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *群ID
       * </pre>
       *
       * <code>string groupId = 5;</code>
       * @param value The bytes for groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object converId_ = "";
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string converId = 6;</code>
       * @return The converId.
       */
      public java.lang.String getConverId() {
        java.lang.Object ref = converId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          converId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string converId = 6;</code>
       * @return The bytes for converId.
       */
      public com.google.protobuf.ByteString
          getConverIdBytes() {
        java.lang.Object ref = converId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          converId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string converId = 6;</code>
       * @param value The converId to set.
       * @return This builder for chaining.
       */
      public Builder setConverId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        converId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string converId = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearConverId() {
        
        converId_ = getDefaultInstance().getConverId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *会话ID
       * </pre>
       *
       * <code>string converId = 6;</code>
       * @param value The bytes for converId to set.
       * @return This builder for chaining.
       */
      public Builder setConverIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        converId_ = value;
        onChanged();
        return this;
      }

      private FridayMessage.MessageContent content_;
      private com.google.protobuf.SingleFieldBuilderV3<
          FridayMessage.MessageContent, FridayMessage.MessageContent.Builder, FridayMessage.MessageContentOrBuilder> contentBuilder_;
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>.proto.MessageContent content = 7;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return contentBuilder_ != null || content_ != null;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>.proto.MessageContent content = 7;</code>
       * @return The content.
       */
      public FridayMessage.MessageContent getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? FridayMessage.MessageContent.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>.proto.MessageContent content = 7;</code>
       */
      public Builder setContent(FridayMessage.MessageContent value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>.proto.MessageContent content = 7;</code>
       */
      public Builder setContent(
          FridayMessage.MessageContent.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>.proto.MessageContent content = 7;</code>
       */
      public Builder mergeContent(FridayMessage.MessageContent value) {
        if (contentBuilder_ == null) {
          if (content_ != null) {
            content_ =
              FridayMessage.MessageContent.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>.proto.MessageContent content = 7;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          content_ = null;
          contentBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>.proto.MessageContent content = 7;</code>
       */
      public FridayMessage.MessageContent.Builder getContentBuilder() {
        
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>.proto.MessageContent content = 7;</code>
       */
      public FridayMessage.MessageContentOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              FridayMessage.MessageContent.getDefaultInstance() : content_;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>.proto.MessageContent content = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          FridayMessage.MessageContent, FridayMessage.MessageContent.Builder, FridayMessage.MessageContentOrBuilder>
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              FridayMessage.MessageContent, FridayMessage.MessageContent.Builder, FridayMessage.MessageContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      private int converType_ = 0;
      /**
       * <pre>
       *请求类型
       * </pre>
       *
       * <code>.proto.ConverType converType = 8;</code>
       * @return The enum numeric value on the wire for converType.
       */
      public int getConverTypeValue() {
        return converType_;
      }
      /**
       * <pre>
       *请求类型
       * </pre>
       *
       * <code>.proto.ConverType converType = 8;</code>
       * @param value The enum numeric value on the wire for converType to set.
       * @return This builder for chaining.
       */
      public Builder setConverTypeValue(int value) {
        converType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求类型
       * </pre>
       *
       * <code>.proto.ConverType converType = 8;</code>
       * @return The converType.
       */
      public FridayMessage.ConverType getConverType() {
        @SuppressWarnings("deprecation")
        FridayMessage.ConverType result = FridayMessage.ConverType.valueOf(converType_);
        return result == null ? FridayMessage.ConverType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *请求类型
       * </pre>
       *
       * <code>.proto.ConverType converType = 8;</code>
       * @param value The converType to set.
       * @return This builder for chaining.
       */
      public Builder setConverType(FridayMessage.ConverType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        converType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求类型
       * </pre>
       *
       * <code>.proto.ConverType converType = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearConverType() {
        
        converType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Message)
    }

    // @@protoc_insertion_point(class_scope:proto.Message)
    private static final FridayMessage.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FridayMessage.Message();
    }

    public static FridayMessage.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FridayMessage.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MessageContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MessageContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <pre>
     *发送方ID
     * </pre>
     *
     * <code>string uid = 2;</code>
     * @return The uid.
     */
    java.lang.String getUid();
    /**
     * <pre>
     *发送方ID
     * </pre>
     *
     * <code>string uid = 2;</code>
     * @return The bytes for uid.
     */
    com.google.protobuf.ByteString
        getUidBytes();

    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.proto.MessageType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.proto.MessageType type = 3;</code>
     * @return The type.
     */
    FridayMessage.MessageType getType();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 4;</code>
     * @return The content.
     */
    java.lang.String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>uint64 time = 5;</code>
     * @return The time.
     */
    long getTime();
  }
  /**
   * Protobuf type {@code proto.MessageContent}
   */
  public  static final class MessageContent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MessageContent)
      MessageContentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageContent.newBuilder() to construct.
    private MessageContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageContent() {
      uid_ = "";
      type_ = 0;
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageContent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageContent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              uid_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 40: {

              time_ = input.readUInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FridayMessage.internal_static_proto_MessageContent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FridayMessage.internal_static_proto_MessageContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FridayMessage.MessageContent.class, FridayMessage.MessageContent.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     *消息ID
     * </pre>
     *
     * <code>uint64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }

    public static final int UID_FIELD_NUMBER = 2;
    private volatile java.lang.Object uid_;
    /**
     * <pre>
     *发送方ID
     * </pre>
     *
     * <code>string uid = 2;</code>
     * @return The uid.
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发送方ID
     * </pre>
     *
     * <code>string uid = 2;</code>
     * @return The bytes for uid.
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.proto.MessageType type = 3;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *消息类型
     * </pre>
     *
     * <code>.proto.MessageType type = 3;</code>
     * @return The type.
     */
    public FridayMessage.MessageType getType() {
      @SuppressWarnings("deprecation")
      FridayMessage.MessageType result = FridayMessage.MessageType.valueOf(type_);
      return result == null ? FridayMessage.MessageType.UNRECOGNIZED : result;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 4;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 4;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 5;
    private long time_;
    /**
     * <pre>
     *消息时间
     * </pre>
     *
     * <code>uint64 time = 5;</code>
     * @return The time.
     */
    public long getTime() {
      return time_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeUInt64(1, id_);
      }
      if (!getUidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, uid_);
      }
      if (type_ != FridayMessage.MessageType.TEXT.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, content_);
      }
      if (time_ != 0L) {
        output.writeUInt64(5, time_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (!getUidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, uid_);
      }
      if (type_ != FridayMessage.MessageType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, content_);
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, time_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof FridayMessage.MessageContent)) {
        return super.equals(obj);
      }
      FridayMessage.MessageContent other = (FridayMessage.MessageContent) obj;

      if (getId()
          != other.getId()) return false;
      if (!getUid()
          .equals(other.getUid())) return false;
      if (type_ != other.type_) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getTime()
          != other.getTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FridayMessage.MessageContent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FridayMessage.MessageContent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FridayMessage.MessageContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FridayMessage.MessageContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FridayMessage.MessageContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FridayMessage.MessageContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FridayMessage.MessageContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FridayMessage.MessageContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FridayMessage.MessageContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FridayMessage.MessageContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FridayMessage.MessageContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FridayMessage.MessageContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FridayMessage.MessageContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MessageContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MessageContent)
        FridayMessage.MessageContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FridayMessage.internal_static_proto_MessageContent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FridayMessage.internal_static_proto_MessageContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FridayMessage.MessageContent.class, FridayMessage.MessageContent.Builder.class);
      }

      // Construct using com.friday.protobuf.FridayMessage.MessageContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        uid_ = "";

        type_ = 0;

        content_ = "";

        time_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FridayMessage.internal_static_proto_MessageContent_descriptor;
      }

      @java.lang.Override
      public FridayMessage.MessageContent getDefaultInstanceForType() {
        return FridayMessage.MessageContent.getDefaultInstance();
      }

      @java.lang.Override
      public FridayMessage.MessageContent build() {
        FridayMessage.MessageContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public FridayMessage.MessageContent buildPartial() {
        FridayMessage.MessageContent result = new FridayMessage.MessageContent(this);
        result.id_ = id_;
        result.uid_ = uid_;
        result.type_ = type_;
        result.content_ = content_;
        result.time_ = time_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FridayMessage.MessageContent) {
          return mergeFrom((FridayMessage.MessageContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FridayMessage.MessageContent other) {
        if (other == FridayMessage.MessageContent.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getUid().isEmpty()) {
          uid_ = other.uid_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FridayMessage.MessageContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FridayMessage.MessageContent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>uint64 id = 1;</code>
       * @return The id.
       */
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>uint64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息ID
       * </pre>
       *
       * <code>uint64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object uid_ = "";
      /**
       * <pre>
       *发送方ID
       * </pre>
       *
       * <code>string uid = 2;</code>
       * @return The uid.
       */
      public java.lang.String getUid() {
        java.lang.Object ref = uid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *发送方ID
       * </pre>
       *
       * <code>string uid = 2;</code>
       * @return The bytes for uid.
       */
      public com.google.protobuf.ByteString
          getUidBytes() {
        java.lang.Object ref = uid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发送方ID
       * </pre>
       *
       * <code>string uid = 2;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方ID
       * </pre>
       *
       * <code>string uid = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        
        uid_ = getDefaultInstance().getUid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送方ID
       * </pre>
       *
       * <code>string uid = 2;</code>
       * @param value The bytes for uid to set.
       * @return This builder for chaining.
       */
      public Builder setUidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uid_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.proto.MessageType type = 3;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.proto.MessageType type = 3;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.proto.MessageType type = 3;</code>
       * @return The type.
       */
      public FridayMessage.MessageType getType() {
        @SuppressWarnings("deprecation")
        FridayMessage.MessageType result = FridayMessage.MessageType.valueOf(type_);
        return result == null ? FridayMessage.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.proto.MessageType type = 3;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(FridayMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型
       * </pre>
       *
       * <code>.proto.MessageType type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 4;</code>
       * @return The content.
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 4;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 4;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 4;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>uint64 time = 5;</code>
       * @return The time.
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>uint64 time = 5;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息时间
       * </pre>
       *
       * <code>uint64 time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.MessageContent)
    }

    // @@protoc_insertion_point(class_scope:proto.MessageContent)
    private static final FridayMessage.MessageContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FridayMessage.MessageContent();
    }

    public static FridayMessage.MessageContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageContent>
        PARSER = new com.google.protobuf.AbstractParser<MessageContent>() {
      @java.lang.Override
      public MessageContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageContent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageContent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public FridayMessage.MessageContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MessageContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MessageContent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\005proto\"\273\001\n\007Message\022\021\n\tre" +
      "questId\030\001 \001(\004\022\013\n\003cid\030\002 \001(\004\022\017\n\007fromUid\030\003 " +
      "\001(\t\022\r\n\005toUid\030\004 \001(\t\022\017\n\007groupId\030\005 \001(\t\022\020\n\010c" +
      "onverId\030\006 \001(\t\022&\n\007content\030\007 \001(\0132\025.proto.M" +
      "essageContent\022%\n\nconverType\030\010 \001(\0162\021.prot" +
      "o.ConverType\"j\n\016MessageContent\022\n\n\002id\030\001 \001" +
      "(\004\022\013\n\003uid\030\002 \001(\t\022 \n\004type\030\003 \001(\0162\022.proto.Me" +
      "ssageType\022\017\n\007content\030\004 \001(\t\022\014\n\004time\030\005 \001(\004" +
      "*:\n\013MessageType\022\010\n\004TEXT\020\000\022\013\n\007PICTURE\020\001\022\t" +
      "\n\005VOICE\020\002\022\t\n\005VIDEO\020\003**\n\nConverType\022\t\n\005LO" +
      "GIN\020\000\022\007\n\003MSG\020\001\022\010\n\004PING\020\002B$\n\023com.friday.p" +
      "rotobufB\rFridayMessageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Message_descriptor,
        new java.lang.String[] { "RequestId", "Cid", "FromUid", "ToUid", "GroupId", "ConverId", "Content", "ConverType", });
    internal_static_proto_MessageContent_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_MessageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MessageContent_descriptor,
        new java.lang.String[] { "Id", "Uid", "Type", "Content", "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
