server:
  port: 8010

spring:
  application:
    name: friday-im-router

netty:
  server:
    port: 8000
    address: 127.0.0.1

zk:
  address: 127.0.0.1:2181
  switch: true
  root: /router
  connection:
    timeout: 15000
