server:
  port: 8010

spring:
  application:
    name: friday-im-router
  # redis 配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 100
        max-active: 100
        max-wait: 1000
        min-idle: 10
  # Kafka 配置
  kafka:
    consumer:
      group-id: test-consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: localhost:9092

netty:
  server:
    port: 8000
    address: 127.0.0.1

zk:
  address: 127.0.0.1:2181
  switch: true
  root: /router
  connection:
    timeout: 15000

#负载均衡策略选择
app:
  router:
    method: com.friday.route.lb.hash.ConsistentHashLoadBalanceHandler

# eureka 配置
eureka:
  client:
    # 是否将自己注册到eureka
    register-with-eureka: false
    # 是否从eureka server获取注册信息
    fetch-registry: false
    # 设置与eureka server 交互的地址 查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    service-url:
      defaultZone: http://localhost:8009/eureka/
  server:
    enable-self-preservation: true
