server:
  port: 8010

spring:
  application:
    name: friday-im-router
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 100
        max-active: 100
        max-wait: 1000
        min-idle: 10

netty:
  server:
    port: 8000
    address: 127.0.0.1

zk:
  address: 127.0.0.1:2181
  switch: true
  root: /router
  connection:
    timeout: 15000

app:
  router:
    method: com.friday.route.lb.hash.ConsistentHashLoadBalanceHandler